In [1]:
import datetime
import numpy as np
import pandas as pd

import pickle

from utils import tf_idf

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
REPORTS_DATA_FILE = "<your path for isw dataset>"

In [4]:
#ISW_OUTPUT_DATA_FILE = "<>"
WEATHER_EVENTS_OUTPUT_DATA_FILE = "<your path for weather dataset>"
tfidf_transformer_model = "tfidf_transformer_"
count_vectorizer_model = "count_vectorizer_"

tfidf_transformer_version = "v1"
count_vectorizer_version = "v1"

In [5]:
def isNaN(num):
    return num != num

In [6]:
df_isw = pd.read_csv(REPORTS_DATA_FILE)

In [7]:
df_isw.head()

,Unnamed: 0.1,Unnamed: 0,id,date,short_url,title,text_title,full_url,html_content,html_content_v6,report_text_lemm,report_text_stemm
0,0,1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty f...,russian offen campaign assess februari twenti...
1,1,1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty f...,russian offen campaign assess februari twenti...
2,2,181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty s...,russian offen campaign assess februari twenti...
3,3,197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty s...,russian offen campaign assess februari twenti...
4,4,1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty e...,russian offen campaign assess februari twenti...

Prepare ISW for Merge

In [8]:
df_isw.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'id', 'date', 'short_url', 'title',
       'text_title', 'full_url', 'html_content', 'html_content_v6',
       'report_text_lemm', 'report_text_stemm'],
      dtype='object')

In [9]:
tfidf = pickle.load(open("tfidf_transformer.pkl", "rb"))
cv = pickle.load(open("count_vectorizer_v1.pkl", "rb"))

In [10]:
import numpy as np

feature_names = cv.get_feature_names_out()

def vector_to_keywords(tfidf_vector, feature_names, top_n=10):
    vector = tfidf_vector.toarray()[0]
    keywords_scores = {
        feature_names[i]: score
        for i, score in enumerate(vector) if score > 0
    }
    sorted_keywords = dict(sorted(keywords_scores.items(), key=lambda x: x[1], reverse=True)[:top_n])
    return sorted_keywords

In [11]:
corpus = df_isw['report_text_lemm'].fillna("").tolist()
X_counts = cv.transform(corpus)
X_tfidf = tfidf.transform(X_counts)

df_isw['keywords_vector'] = [
    vector_to_keywords(row, feature_names)
    for row in X_tfidf
]

In [12]:
df_isw['keywords_vector'].median

<bound method NDFrame._add_numeric_operations.<locals>.median of 0       {'februari': 0.46111364585068776, 'twenty': 0....
1       {'februari': 0.4046017827595065, 'twenty': 0.3...
2       {'februari': 0.4393921318104611, 'twenty': 0.3...
3       {'februari': 0.46287074916824467, 'twenty': 0....
4       {'februari': 0.4839400704975043, 'twenty': 0.3...
5       {'kyiv': 0.35674988512391226, 'envelop': 0.251...
6       {'kyiv': 0.46916007021450795, 'envelop': 0.280...
7       {'kyiv': 0.39762398397265836, 'chernihiv': 0.1...
8       {'kyiv': 0.3388343289039712, 'congest': 0.2137...
9       {'kyiv': 0.3302482081051005, 'hour': 0.2551019...
10      {'kyiv': 0.36879085148122026, 'lubni': 0.30245...
11      {'zaporizhya': 0.3179277436294645, 'kyiv': 0.2...
12      {'zaporizhya': 0.34810198212648547, 'kyiv': 0....
13      {'kyiv': 0.3115942802788235, 'mykolayiv': 0.17...
14      {'kyiv': 0.38148676174206136, 'ten': 0.3786245...
15      {'eleven': 0.48992752914271925, 'belarusian': ...
16      {'twelve': 0.4284836265667075, 'kyiv': 0.27821...
17      {'thirteen': 0.4627593465678543, 'kyiv': 0.243...
18      {'fourteen': 0.3722382126510688, 'kyiv': 0.292...
19      {'fifteen': 0.37816568638445547, 'kyiv': 0.273...
20      {'sixteen': 0.4721284552352872, 'kyiv': 0.2767...
21      {'seventeen': 0.552783505330319, 'sixteen': 0....
22      {'eighteen': 0.4428765690487497, 'mykolayiv': ...
23      {'nineteen': 0.2518709108546696, 'stalem': 0.2...
24      {'twenty': 0.2660607264338948, 'staff': 0.2175...
25      {'twenty': 0.43707161379182335, 'kyiv': 0.2403...
26      {'twenty': 0.4025272312399261, 'kyiv': 0.23804...
27      {'twenty': 0.22976348063108004, 'irpin': 0.218...
28      {'twenty': 0.4183047310321457, 'mariupol': 0.2...
29      {'rudskoi': 0.5961058249030141, 'twenty': 0.29...
30      {'kyiv': 0.25456155377562406, 'mariupol': 0.21...
31      {'twenty': 0.4438988020806742, 'seven': 0.2783...
32      {'twenty': 0.3811337001153887, 'kyiv': 0.29473...
33      {'kyiv': 0.3017884726239604, 'nine': 0.2230149...
34      {'kyiv': 0.29459927227401717, 'hour': 0.279283...
35      {'thirty': 0.33469024866794594, 'kyiv': 0.2680...
36      {'april': 0.31714708699626976, 'kyiv': 0.25675...
37      {'april': 0.6155697209667357, 'paus': 0.175363...
38      {'april': 0.36467923030473626, 'kyiv': 0.24602...
39      {'april': 0.44888914212861913, 'izyum': 0.2319...
40      {'april': 0.3534687444166754, 'izyum': 0.26984...
41      {'april': 0.4148616409005312, 'izyum': 0.23448...
42      {'april': 0.47502781822250156, 'passport': 0.1...
43      {'april': 0.4968547736134757, 'mariupol': 0.22...
44      {'dod': 0.27630154906815474, 'april': 0.256820...
45      {'april': 0.5031310713960954, 'ten': 0.2497924...
46      {'dvornikov': 0.7595047536311179, 'command': 0...
47      {'april': 0.4554464527633843, 'twelve': 0.3209...
48      {'april': 0.4659434145089679, 'thirteen': 0.42...
49      {'april': 0.5548728956198907, 'fourteen': 0.27...
50      {'april': 0.41779218040911, 'fifteen': 0.27856...
51      {'izyum': 0.2574258093124926, 'april': 0.21918...
52      {'april': 0.4581355185408796, 'seventeen': 0.2...
53      {'april': 0.41787712354475237, 'eighteen': 0.3...
54      {'april': 0.36410943111349936, 'nineteen': 0.3...
55      {'april': 0.43016921745647657, 'libyan': 0.274...
56      {'april': 0.3341248458084701, 'mariupol': 0.32...
57      {'april': 0.4033517789792619, 'minnekaev': 0.2...
58      {'april': 0.42748165998186033, 'izyum': 0.2393...
59      {'april': 0.3448635654846704, 'azovst': 0.2930...
60      {'april': 0.4186025084169425, 'twenty': 0.2434...
61      {'april': 0.3683199374060302, 'transnistria': ...
62      {'april': 0.40223760181173285, 'transnistria':...
63      {'april': 0.44917804967848357, 'twenty': 0.254...
64      {'april': 0.4071029049070671, 'transnistria': ...
65      {'april': 0.32884327050972495, 'izyum': 0.3282...
66      {'may': 0.24969006686112183, 'csto': 0.2408180...
67      {'may': 0.32965447768839706, 'izyum': 0.304555...
68      {'may': 0.3345848624512316, 'mariupol': 0.2657...
69      {'may': 0.3127349065461837, 'mariupol': 0.2513...
70      {'toretsk': 0.3141178337755519, 'may': 0.29797...
71      {'may': 0.30930150505006926, 'hour': 0.2150218...
72      {'may': 0.3120206298944436, 'mariupol': 0.1790...
73      {'may': 0.3183950039777112, 'mariupol': 0.2011...
74      {'may': 0.2543886473599017, 'btg': 0.216320730...
75      {'belarusian': 0.2830241553457209, 'ten': 0.27...
76      {'eleven': 0.3051702737887508, 'may': 0.236281...
77      {'voevodivka': 0.3758035430233535, 'twelve': 0...
78      {'thirteen': 0.2554114395759944, 'attempt': 0....
79      {'may': 0.23802124767635327, 'severodonetsk': ...
80      {'izyum': 0.22858717044759794, 'severodonetsk'...
81      {'sixteen': 0.35089875908672824, 'may': 0.2593...
82      {'seventeen': 0.29455546629208645, 'surrend': ...
83      {'mariupol': 0.2973485269981303, 'azovst': 0.2...
84      {'nineteen': 0.2895145370723108, 'gromov': 0.2...
85      {'may': 0.24016505178081496, 'severodonetsk': ...
86      {'severodonetsk': 0.3570930337932799, 'mariupo...
87      {'popasna': 0.24516130625318502, 'may': 0.2303...
88      {'may': 0.2305603440346716, 'twenty': 0.188133...
89      {'twenty': 0.2512618213635764, 'may': 0.218034...
90      {'severodonetsk': 0.26090834608087876, 'may': ...
91      {'severodonetsk': 0.2549430947295015, 'six': 0...
92      {'severodonetsk': 0.36239459794116236, 'may': ...
93      {'severodonetsk': 0.29842527036538713, 'may': ...
94      {'may': 0.2971511889939314, 'nine': 0.27916744...
95      {'junior': 0.26028493768157696, 'severodonetsk...
96      {'severodonetsk': 0.2508934379747649, 'gubarev...
97      {'june': 0.2834325510459503, 'severodonetsk': ...
98      {'june': 0.29221437184191595, 'severodonetsk':...
99      {'boytsovyi': 0.390414957365639, 'murz': 0.356...
100     {'june': 0.33351385543498824, 'severodonetsk':...
101     {'kutuzov': 0.4047041900365778, 'june': 0.3636...
102     {'june': 0.5079171216044528, 'severodonetsk': ...
103     {'june': 0.33234683508039975, 'severodonetsk':...
104     {'june': 0.46605445923015454, 'sviatohirsk': 0...
105     {'june': 0.37076256122946755, 'mine': 0.172914...
106     {'june': 0.37088802264562454, 'ten': 0.2617913...
107     {'june': 0.35599495820272, 'eleven': 0.3163403...
108     {'june': 0.38110500798242347, 'twelve': 0.3124...
109     {'june': 0.34211993332447527, 'izvestia': 0.26...
110     {'june': 0.2737346489943214, 'fourteen': 0.258...
111     {'june': 0.395151904380991, 'fifteen': 0.24664...
112     {'june': 0.3251475172535544, 'seventeen': 0.27...
113     {'june': 0.3251475172535544, 'seventeen': 0.27...
114     {'june': 0.39331819564936227, 'eighteen': 0.38...
115     {'nineteen': 0.3200518797919443, 'june': 0.283...
116     {'june': 0.34015765222818134, 'severodonetsk':...
117     {'june': 0.3500820119144472, 'dvornikov': 0.24...
118     {'june': 0.35966652651834097, 'lysychansk': 0....
119     {'june': 0.39201786110739906, 'lysychansk': 0....
120     {'june': 0.3285548541930574, 'lysychansk': 0.3...
121     {'june': 0.3491038912690371, 'skibitski': 0.18...
122     {'june': 0.37939829487869603, 'zhidko': 0.2880...
123     {'june': 0.3564979584083497, 'kremenchuk': 0.2...
124     {'june': 0.32554946351798086, 'lysychansk': 0....
125     {'june': 0.26314372372439304, 'gubernia': 0.25...
126     {'june': 0.40700550364763605, 'island': 0.2384...
127     {'juli': 0.2629361293615399, 'enlarg': 0.21594...
128     {'lysychansk': 0.36259296651276585, 'juli': 0....
129     {'juli': 0.555402418354267, 'lysychansk': 0.26...
130     {'juli': 0.5164998474873393, 'girkin': 0.29434...
131     {'juli': 0.33275655865194376, 'patrushev': 0.3...
132     {'juli': 0.40759451990023027, 'km': 0.18088152...
133     {'juli': 0.4701488620305266, 'km': 0.219073865...
134     {'paus': 0.30923265274216455, 'juli': 0.300902...
135     {'juli': 0.3969016893366965, 'lb': 0.149161128...
136     {'rybar': 0.3055864897230137, 'correspond': 0....
137     {'juli': 0.4706539205338083, 'eleven': 0.33642...
138     {'juli': 0.47745140953054754, 'twelve': 0.2520...
139     {'juli': 0.3356063721086719, 'thirteen': 0.228...
140     {'juli': 0.4297012776759891, 'fourteen': 0.275...
141     {'juli': 0.5408060248676375, 'fifteen': 0.2721...
142     {'juli': 0.5289535391484846, 'sixteen': 0.3255...
143     {'juli': 0.4531605866710493, 'seventeen': 0.41...
144     {'juli': 0.3435709302360111, 'eighteen': 0.325...
145     {'nineteen': 0.3152575145261608, 'juli': 0.309...
146     {'juli': 0.42520359915619427, 'e40': 0.2100861...
147     {'juli': 0.5390653603549336, 'twenty': 0.21226...
148     {'juli': 0.44017786157792166, 'twenty': 0.2224...
149     {'juli': 0.4997964971579426, 'twenty': 0.26644...
150     {'juli': 0.49467322105510925, 'twenty': 0.2290...
151     {'juli': 0.35216229251676323, 'novoluhansk': 0...
152     {'juli': 0.3573138563491741, 'twenty': 0.21667...
153     {'juli': 0.44962434147516267, 'twenty': 0.2097...
154     {'juli': 0.42812082306478666, 'twenty': 0.2282...
155     {'juli': 0.5000572713589998, 'twenty': 0.21659...
156     {'juli': 0.42590771778949876, 'railroad': 0.22...
157     {'juli': 0.5136246253924905, 'thirty': 0.20184...
158     {'august': 0.3333519499258009, 'kherson': 0.15...
159     {'august': 0.3900420058324298, 'butivka': 0.18...
160     {'august': 0.3615347183407617, 'vote': 0.24949...
161     {'gromov': 0.3769172099873564, 'august': 0.370...
162     {'august': 0.2996438620374105, 'passport': 0.2...
163     {'august': 0.45242303806595463, 'npp': 0.16554...
164     {'august': 0.4749302542355484, 'vote': 0.16691...
165     {'august': 0.4884511958737279, 'nuclear': 0.15...
166     {'august': 0.38019666905979493, 'km': 0.187410...
167     {'august': 0.4551014398136223, 'uzbek': 0.2265...
168     {'august': 0.4557054945809853, 'eleven': 0.281...
169     {'august': 0.4244482809253498, 'dobropillya': ...
170     {'august': 0.35928139506100437, 'thirteen': 0....
171     {'august': 0.38159203814115006, 'recruit': 0.2...
172     {'august': 0.5264075307398871, 'fifteen': 0.21...
173     {'august': 0.3333856094074991, 'sixteen': 0.24...
174     {'august': 0.29624535349816716, 'seventeen': 0...
175     {'august': 0.5216299590325906, 'eighteen': 0.3...
176     {'august': 0.48994787186353955, 'nineteen': 0....
177     {'august': 0.42283984678193415, 'twenty': 0.17...
178     {'august': 0.4403555016722906, 'volunt': 0.210...
179     {'august': 0.41003880319634994, 'twenty': 0.24...
180     {'august': 0.4289482502083877, 'twenty': 0.229...
181     {'august': 0.3657448310950671, 'twenty': 0.180...
182     {'august': 0.41529945534433865, 'spetznaz': 0....
183     {'august': 0.5289786163083696, 'six': 0.259479...
184     {'august': 0.37485621443408096, '3rd': 0.26892...
185     {'august': 0.3816524551620873, 'beglov': 0.291...
186     {'august': 0.5214533504983229, 'nine': 0.26690...
187     {'august': 0.46451615202569335, 'thirty': 0.16...
188     {'august': 0.3148817309137674, 'school': 0.229...
189     {'septemb': 0.30348456956304415, 'kherson': 0....
190     {'septemb': 0.45272086946945145, 'milblogg': 0...
191     {'septemb': 0.40398720680030165, 'kherson': 0....
192     {'septemb': 0.32656025783020887, 'vysokopillya...
193     {'septemb': 0.43544418365735194, 'kherson': 0....
194     {'septemb': 0.42538151781263095, 'iaea': 0.203...
195     {'septemb': 0.440444308314713, 'kherson': 0.16...
196     {'septemb': 0.36405133013929214, 'balakliya': ...
197     {'septemb': 0.37995780393991, 'burluk': 0.2106...
198     {'septemb': 0.352440140317004, 'ten': 0.222695...
199     {'septemb': 0.292199592954443, 'eleven': 0.258...
200     {'septemb': 0.32868023522013673, 'twelve': 0.2...
201     {'septemb': 0.22467533710902957, 'defeat': 0.2...
202     {'septemb': 0.3153856579969378, 'fourteen': 0....
203     {'septemb': 0.22726245318459468, 'river': 0.15...
204     {'septemb': 0.4722608878561707, 'sixteen': 0.3...
205     {'septemb': 0.3778434069848092, 'seventeen': 0...
206     {'septemb': 0.28741491467237285, 'eighteen': 0...
207     {'septemb': 0.46816451168775414, 'nineteen': 0...
208     {'septemb': 0.3821100331955744, 'conscript': 0...
209     {'septemb': 0.30120041735989417, 'mobil': 0.22...
210     {'septemb': 0.34051472181101033, 'mobil': 0.23...
211     {'septemb': 0.32896594329103046, 'mobil': 0.32...
212     {'septemb': 0.2979781213472142, 'mobil': 0.289...
213     {'involuntari': 0.29704427139077116, 'mobil': ...
214     {'septemb': 0.4456276630005524, 'twenty': 0.27...
215     {'septemb': 0.4591774938120232, 'seven': 0.254...
216     {'septemb': 0.4273112719540893, 'eight': 0.223...
217     {'septemb': 0.35578507760808475, 'mobil': 0.28...
218     {'septemb': 0.41137812955702546, 'mobil': 0.25...
219     {'octob': 0.3053650805160452, 'lyman': 0.27409...
220     {'putin': 0.27901777250336135, 'kadyrov': 0.25...
221     {'octob': 0.5473065044556679, 'mobil': 0.16082...
222     {'mobil': 0.3134825573551811, 'octob': 0.29780...
223     {'octob': 0.46775858885667165, 'putin': 0.2165...
224     {'octob': 0.5218788438191191, 'mobil': 0.18670...
225     {'octob': 0.41423596652993333, 'mobil': 0.2140...
226     {'octob': 0.4196273697122903, 'mobil': 0.22304...
227     {'surovikin': 0.3218001452091975, 'putin': 0.2...
228     {'octob': 0.617984250333884, 'ten': 0.24911930...
229     {'octob': 0.4028474333293956, 'eleven': 0.2697...
230     {'octob': 0.3985974884439587, 'twelve': 0.2753...
231     {'octob': 0.36948204920822647, 'thirteen': 0.3...
232     {'octob': 0.40556779654752856, 'fourteen': 0.3...
233     {'octob': 0.40805893343414296, 'fifteen': 0.22...
234     {'must': 0.19748701363711949, 'requir': 0.1719...
235     {'octob': 0.536318178953237, 'seventeen': 0.42...
236     {'octob': 0.5285652100898114, 'eighteen': 0.32...
237     {'octob': 0.3471698870075259, 'mobil': 0.28405...
238     {'octob': 0.46381237660376257, 'iranian': 0.27...
239     {'octob': 0.42747645298124226, 'mobil': 0.2014...
240     {'octob': 0.5211576860888448, 'twenty': 0.2492...
241     {'dirti': 0.32436939166190865, 'shoigu': 0.321...
242     {'octob': 0.6251738974679866, 'twenty': 0.3187...
243     {'octob': 0.36364824933799594, 'prigozhin': 0....
244     {'octob': 0.44430475281567955, 'twenty': 0.227...
245     {'octob': 0.4276962791814257, 'twenty': 0.2253...
246     {'octob': 0.41794498815329184, 'lapin': 0.2610...
247     {'lapin': 0.35891536779706945, 'octob': 0.3096...
248     {'conscript': 0.2691899380844857, 'putin': 0.2...
249     {'octob': 0.6113075744199101, 'thirty': 0.3930...
250     {'novemb': 0.34588043088801346, 'mordichev': 0...
251     {'novemb': 0.3565219277477591, 'znpp': 0.16234...
252     {'novemb': 0.4415175818436892, 'hromov': 0.241...
253     {'novemb': 0.5389876272024803, 'mobil': 0.2202...
254     {'novemb': 0.4445687326334715, 'prigozhin': 0....
255     {'nuclear': 0.6127475007221802, 'threat': 0.22...
256     {'novemb': 0.691285164989806, 'prigozhin': 0.1...
257     {'novemb': 0.48422482066555567, 'patrushev': 0...
258     {'novemb': 0.3305538826203821, 'surovikin': 0....
259     {'novemb': 0.40905473472061643, 'ten': 0.24829...
260     {'novemb': 0.4695625316413698, 'eleven': 0.413...
261     {'novemb': 0.3840757083880101, 'twelve': 0.265...
262     {'uaf': 0.48635065903435243, 'surovikin': 0.24...
263     {'novemb': 0.5558345712458562, 'fourteen': 0.3...
264     {'novemb': 0.402402107602935, 'fifteen': 0.212...
265     {'novemb': 0.46888207841035084, 'sixteen': 0.2...
266     {'novemb': 0.45705084385733374, 'seventeen': 0...
267     {'novemb': 0.41317663355881884, 'eighteen': 0....
268     {'novemb': 0.32337085751649375, 'nineteen': 0....
269     {'milblogg': 0.4177754322851975, 'putin': 0.23...
270     {'novemb': 0.5922619598260667, 'twenty': 0.339...
271     {'novemb': 0.3823862284003271, 'twenty': 0.193...
272     {'novemb': 0.413216170106988, 'twenty': 0.1912...
273     {'novemb': 0.3336722935889671, 'novosilka': 0....
274     {'novemb': 0.522070007951484, 'twenty': 0.3221...
275     {'novemb': 0.3654934335353232, 'sarkisyan': 0....
276     {'spit': 0.2678863053886411, 'array': 0.209652...
277     {'novemb': 0.6072501031650744, 'twenty': 0.337...
278     {'novemb': 0.4714216891003097, 'nine': 0.23491...
279     {'novemb': 0.44489892531652936, 'thirty': 0.18...
280     {'decemb': 0.29739064417220495, 'hromov': 0.24...
281     {'decemb': 0.3214412643819454, 'negoti': 0.177...
282     {'decemb': 0.38639101845348867, 'poll': 0.1983...
283     {'decemb': 0.38457420941913223, 'winter': 0.28...
284     {'decemb': 0.37386443364012406, 'engels': 0.32...
285     {'decemb': 0.6406355359689961, 'mobil': 0.1744...
286     {'decemb': 0.4232844299726991, 'putin': 0.2132...
287     {'decemb': 0.40627797246001757, 'putin': 0.218...
288     {'decemb': 0.3884880634901221, 'putin': 0.2420...
289     {'decemb': 0.46398301725199287, 'ten': 0.20997...
290     {'belarusian': 0.7698985472395367, 'lukashenko...
291     {'decemb': 0.5091304554339405, 'twelve': 0.274...
292     {'decemb': 0.40931734455239405, 'thirteen': 0....
293     {'decemb': 0.33592769906059106, 'fourteen': 0....
294     {'decemb': 0.3421189622107382, 'fifteen': 0.18...
295     {'decemb': 0.4096501180512414, 'sixteen': 0.28...
296     {'decemb': 0.3133924043676852, 'seventeen': 0....
297     {'decemb': 0.33521739155685043, 'prigozhin': 0...
298     {'decemb': 0.5078962631567868, 'nineteen': 0.3...
299     {'decemb': 0.3776697241994506, 'putin': 0.2789...
300     {'decemb': 0.41793205282251555, 'shoigu': 0.30...
301     {'decemb': 0.39651564181430243, 'putin': 0.204...
302     {'decemb': 0.5427179086102977, 'mdcoa': 0.3078...
303     {'decemb': 0.47005269672472083, 'twenty': 0.23...
304     {'decemb': 0.47005269672472083, 'twenty': 0.23...
305     {'decemb': 0.47437188509346395, 'twenty': 0.23...
306     {'decemb': 0.3549727859285009, 'lavrov': 0.227...
307     {'decemb': 0.4772639068315045, 'twenty': 0.233...
308     {'decemb': 0.5297447255561253, 'twenty': 0.292...
309     {'decemb': 0.5142531729360554, 'thirty': 0.219...
310     {'decemb': 0.5025516771811299, 'thirty': 0.228...
311     {'januari': 0.6156348252735719, 'ten': 0.30315...
312     {'januari': 0.5822684912953494, 'opsec': 0.164...
313     {'januari': 0.49946975754784345, 'pokrovsk': 0...
314     {'januari': 0.5844728335178305, 'kurakhov': 0....
315     {'januari': 0.48488121064259704, 'indian': 0.2...
316     {'januari': 0.7071632282609368, 'kursk': 0.176...
317     {'toretsk': 0.4754889852617776, 'januari': 0.4...
318     {'januari': 0.5925969563665405, 'drone': 0.273...
319     {'januari': 0.5371814001467012, 'near': 0.1914...
320     {'januari': 0.6156348252735719, 'ten': 0.30315...
321     {'januari': 0.5021457371892086, 'eleven': 0.34...
322     {'januari': 0.596731641147839, 'twelve': 0.347...
323     {'januari': 0.529016429081002, 'thirteen': 0.3...
324     {'januari': 0.4978730132605677, 'fourteen': 0....
325     {'januari': 0.5387854310558939, 'fifteen': 0.2...
326     {'januari': 0.5901698195004936, 'sixteen': 0.3...
327     {'januari': 0.5270879381898529, 'seventeen': 0...
328     {'januari': 0.49470713658479926, 'eighteen': 0...
329     {'januari': 0.5945713822798332, 'nineteen': 0....
330     {'januari': 0.6302867351766557, 'twenty': 0.30...
331     {'januari': 0.6118296415523562, 'twenty': 0.36...
332     {'januari': 0.5375028604109047, 'twenty': 0.34...
333     {'januari': 0.5952378371506402, 'twenty': 0.36...
334     {'januari': 0.508941825281007, 'twenty': 0.301...
335     {'januari': 0.4629703073104113, 'twenty': 0.27...
336     {'januari': 0.47510855968594234, 'twenty': 0.3...
337     {'januari': 0.5586817548373989, 'twenty': 0.32...
338     {'januari': 0.5156006420186257, 'twenty': 0.30...
339     {'januari': 0.5388546038639851, 'nine': 0.2937...
340     {'januari': 0.46824468788452883, 'lukyanov': 0...
341     {'januari': 0.5157696456950447, 'thirty': 0.30...
342     {'februari': 0.46904003002365924, 'januari': 0...

In [13]:
df_isw.tail()

,Unnamed: 0.1,Unnamed: 0,id,date,short_url,title,text_title,full_url,html_content,html_content_v6,report_text_lemm,report_text_stemm,keywords_vector
1459,1459,736,737,2026-02-25,2026_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty f...,russian offen campaign assess februari twenti...,"{'februari': 0.4046017827595065, 'twenty': 0.3..."
1460,1460,827,828,2026-02-26,2026_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty s...,russian offen campaign assess februari twenti...,"{'februari': 0.4393921318104611, 'twenty': 0.3..."
1461,1461,1012,1013,2026-02-27,2026_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty s...,russian offen campaign assess februari twenti...,"{'februari': 0.46287074916824467, 'twenty': 0...."
1462,1462,470,471,2026-02-28,2026_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty e...,russian offen campaign assess februari twenti...,"{'februari': 0.4839400704975043, 'twenty': 0.3..."
1463,1463,1188,1189,2026-03-01,2026_03_01,"Russian Offensive Campaign Assessment, March 1...","Russian Offensive Campaign Assessment, March 1...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, March 1...",russian offens campaign ass march isw option ...,russian offen campaign assess march isw optio...,"{'kyiv': 0.35674988512391226, 'envelop': 0.251..."

In [14]:
df_isw["date_datetime"] = pd.to_datetime(df_isw["date"])

In [15]:
df_isw['date_tomorrow_datetime'] = df_isw['date_datetime'].apply(lambda x: x+datetime.timedelta(days=1))

In [16]:
df_isw = df_isw.rename(columns = {"date_datetime":"report_date"})
#df_isw.to_csv(f"{ISW_OUTPUT_DATA_FILE}", sep=";", index=False)

Prepare Events for Merge

In [17]:
EVENTS_DATA_FILE = "<your path for alarms dataset>"

In [18]:
df_events = pd.read_csv(EVENTS_DATA_FILE, sep=";")

In [19]:
df_events.columns

Index(['id', 'merged_id', 'region_id', 'region_title', 'region_city',
       'all_region', 'start', 'end', 'original_alarms'],
      dtype='object')

In [20]:
df_events["type"] = "alarm"

In [21]:
df_events.columns

Index(['id', 'merged_id', 'region_id', 'region_title', 'region_city',
       'all_region', 'start', 'end', 'original_alarms', 'type'],
      dtype='object')

In [22]:
df_events_v2 = df_events.drop(["id","region_id","merged_id"],axis=1)

In [23]:
df_events_v2.head(5)

,region_title,region_city,all_region,start,end,original_alarms,type
0,Львівська область,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28,"[""52432""]",alarm
1,Чернігівська область,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43,"[""53292""]",alarm
2,Вінницька область,Вінницька обл.,1,2022-02-24 15:40:42,2022-02-24 16:10:42,"[""52080""]",alarm
3,Харківська область,Харківська обл.,1,2022-02-24 20:11:47,2022-02-24 20:59:47,"[""52857""]",alarm
4,Тернопільська область,Тернопільська обл.,1,2022-02-25 01:59:36,2022-02-25 09:00:19,"[""52700""]",alarm

In [24]:
df_events_v2["start_time"] = df_events_v2.apply(lambda x: x["start"] if not isNaN(x["start"]) else x["event_time"] , axis=1)
df_events_v2["end_time"] = df_events_v2.apply(lambda x: x["end"] if not isNaN(x["end"]) else x["event_time"], axis=1)

In [25]:
df_events_v2["start_time"] = pd.to_datetime(df_events_v2["start"])
df_events_v2["end_time"] = pd.to_datetime(df_events_v2["end"])

In [26]:
df_events_v2.head()

,region_title,region_city,all_region,start,end,original_alarms,type,start_time,end_time
0,Львівська область,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28,"[""52432""]",alarm,2022-02-24 07:43:17,2022-02-24 09:52:28
1,Чернігівська область,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43,"[""53292""]",alarm,2022-02-24 14:00:43,2022-02-24 17:11:43
2,Вінницька область,Вінницька обл.,1,2022-02-24 15:40:42,2022-02-24 16:10:42,"[""52080""]",alarm,2022-02-24 15:40:42,2022-02-24 16:10:42
3,Харківська область,Харківська обл.,1,2022-02-24 20:11:47,2022-02-24 20:59:47,"[""52857""]",alarm,2022-02-24 20:11:47,2022-02-24 20:59:47
4,Тернопільська область,Тернопільська обл.,1,2022-02-25 01:59:36,2022-02-25 09:00:19,"[""52700""]",alarm,2022-02-25 01:59:36,2022-02-25 09:00:19

In [27]:
df_events_v2["start_hour"] = df_events_v2['start_time'].dt.floor('H')
df_events_v2["end_hour"] = df_events_v2['end_time'].dt.ceil('H')

In [28]:
df_events_v2.columns

Index(['region_title', 'region_city', 'all_region', 'start', 'end',
       'original_alarms', 'type', 'start_time', 'end_time', 'start_hour',
       'end_hour'],
      dtype='object')

In [29]:
df_events_v2["start_hour"] = df_events_v2["start_hour"].apply(lambda x: x if pd.notna(x) else None)
df_events_v2["end_hour"] = df_events_v2["end_hour"].apply(lambda x: x if pd.notna(x) else None)

In [30]:
df_events_v2["day_date"] = df_events_v2["start_time"].dt.date

df_events_v2["start_hour_datetimeEpoch"] = df_events_v2["start_hour"].apply(
    lambda x: int(x.timestamp()) if pd.notna(x) else None
)

df_events_v2["end_hour_datetimeEpoch"] = df_events_v2["end_hour"].apply(
    lambda x: int(x.timestamp()) if pd.notna(x) else None
)
df_events_v2.head()

,region_title,region_city,all_region,start,end,original_alarms,type,start_time,end_time,start_hour,end_hour,day_date,start_hour_datetimeEpoch,end_hour_datetimeEpoch
0,Львівська область,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28,"[""52432""]",alarm,2022-02-24 07:43:17,2022-02-24 09:52:28,2022-02-24 07:00:00,2022-02-24 10:00:00,2022-02-24,1645686000,1645696800
1,Чернігівська область,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43,"[""53292""]",alarm,2022-02-24 14:00:43,2022-02-24 17:11:43,2022-02-24 14:00:00,2022-02-24 18:00:00,2022-02-24,1645711200,1645725600
2,Вінницька область,Вінницька обл.,1,2022-02-24 15:40:42,2022-02-24 16:10:42,"[""52080""]",alarm,2022-02-24 15:40:42,2022-02-24 16:10:42,2022-02-24 15:00:00,2022-02-24 17:00:00,2022-02-24,1645714800,1645722000
3,Харківська область,Харківська обл.,1,2022-02-24 20:11:47,2022-02-24 20:59:47,"[""52857""]",alarm,2022-02-24 20:11:47,2022-02-24 20:59:47,2022-02-24 20:00:00,2022-02-24 21:00:00,2022-02-24,1645732800,1645736400
4,Тернопільська область,Тернопільська обл.,1,2022-02-25 01:59:36,2022-02-25 09:00:19,"[""52700""]",alarm,2022-02-25 01:59:36,2022-02-25 09:00:19,2022-02-25 01:00:00,2022-02-25 10:00:00,2022-02-25,1645750800,1645783200

In [31]:
df_events_v2["day_date"] = df_events_v2["start_time"].dt.date

df_events_v2["start_hour_datetimeEpoch"] = df_events_v2['start_hour'].apply(lambda x: int(x.strftime('%s'))  if not isNaN(x) else None)
df_events_v2["end_hour_datetimeEpoch"] = df_events_v2['end_hour'].apply(lambda x: int(x.strftime('%s'))  if not isNaN(x) else None)

df_events_v2.head(10)

,region_title,region_city,all_region,start,end,original_alarms,type,start_time,end_time,start_hour,end_hour,day_date,start_hour_datetimeEpoch,end_hour_datetimeEpoch
0,Львівська область,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28,"[""52432""]",alarm,2022-02-24 07:43:17,2022-02-24 09:52:28,2022-02-24 07:00:00,2022-02-24 10:00:00,2022-02-24,1645678800,1645689600
1,Чернігівська область,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43,"[""53292""]",alarm,2022-02-24 14:00:43,2022-02-24 17:11:43,2022-02-24 14:00:00,2022-02-24 18:00:00,2022-02-24,1645704000,1645718400
2,Вінницька область,Вінницька обл.,1,2022-02-24 15:40:42,2022-02-24 16:10:42,"[""52080""]",alarm,2022-02-24 15:40:42,2022-02-24 16:10:42,2022-02-24 15:00:00,2022-02-24 17:00:00,2022-02-24,1645707600,1645714800
3,Харківська область,Харківська обл.,1,2022-02-24 20:11:47,2022-02-24 20:59:47,"[""52857""]",alarm,2022-02-24 20:11:47,2022-02-24 20:59:47,2022-02-24 20:00:00,2022-02-24 21:00:00,2022-02-24,1645725600,1645729200
4,Тернопільська область,Тернопільська обл.,1,2022-02-25 01:59:36,2022-02-25 09:00:19,"[""52700""]",alarm,2022-02-25 01:59:36,2022-02-25 09:00:19,2022-02-25 01:00:00,2022-02-25 10:00:00,2022-02-25,1645743600,1645776000
5,Вінницька область,Вінницька обл.,1,2022-02-25 04:01:42,2022-02-25 08:35:42,"[""52081""]",alarm,2022-02-25 04:01:42,2022-02-25 08:35:42,2022-02-25 04:00:00,2022-02-25 09:00:00,2022-02-25,1645754400,1645772400
6,Харківська область,Харківська обл.,1,2022-02-25 04:56:47,2022-02-25 05:40:47,"[""52858""]",alarm,2022-02-25 04:56:47,2022-02-25 05:40:47,2022-02-25 04:00:00,2022-02-25 06:00:00,2022-02-25,1645754400,1645761600
7,Чернігівська область,Чернігівська обл.,1,2022-02-25 06:46:43,2022-02-25 06:52:43,"[""53293""]",alarm,2022-02-25 06:46:43,2022-02-25 06:52:43,2022-02-25 06:00:00,2022-02-25 07:00:00,2022-02-25,1645761600,1645765200
8,Львівська область,Львівська обл.,1,2022-02-25 06:53:17,2022-02-25 07:56:28,"[""52431""]",alarm,2022-02-25 06:53:17,2022-02-25 07:56:28,2022-02-25 06:00:00,2022-02-25 08:00:00,2022-02-25,1645761600,1645768800
9,Київська область,Київ,0,2022-02-25 07:19:04,2022-02-25 07:49:04,"[""72852""]",alarm,2022-02-25 07:19:04,2022-02-25 07:49:04,2022-02-25 07:00:00,2022-02-25 08:00:00,2022-02-25,1645765200,1645768800

In [32]:
df_events_v2["type"].head(5)

0    alarm
1    alarm
2    alarm
3    alarm
4    alarm
Name: type, dtype: object

In [33]:
df_events_v2["type"].shape

(76232,)

In [34]:
df_events_v2[~(df_events_v2["type"]=="alarm")].shape

(0, 14)

In [35]:
df_events_v2[~(df_events_v2["type"]!="alarm")].head(5)

,region_title,region_city,all_region,start,end,original_alarms,type,start_time,end_time,start_hour,end_hour,day_date,start_hour_datetimeEpoch,end_hour_datetimeEpoch
0,Львівська область,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28,"[""52432""]",alarm,2022-02-24 07:43:17,2022-02-24 09:52:28,2022-02-24 07:00:00,2022-02-24 10:00:00,2022-02-24,1645678800,1645689600
1,Чернігівська область,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43,"[""53292""]",alarm,2022-02-24 14:00:43,2022-02-24 17:11:43,2022-02-24 14:00:00,2022-02-24 18:00:00,2022-02-24,1645704000,1645718400
2,Вінницька область,Вінницька обл.,1,2022-02-24 15:40:42,2022-02-24 16:10:42,"[""52080""]",alarm,2022-02-24 15:40:42,2022-02-24 16:10:42,2022-02-24 15:00:00,2022-02-24 17:00:00,2022-02-24,1645707600,1645714800
3,Харківська область,Харківська обл.,1,2022-02-24 20:11:47,2022-02-24 20:59:47,"[""52857""]",alarm,2022-02-24 20:11:47,2022-02-24 20:59:47,2022-02-24 20:00:00,2022-02-24 21:00:00,2022-02-24,1645725600,1645729200
4,Тернопільська область,Тернопільська обл.,1,2022-02-25 01:59:36,2022-02-25 09:00:19,"[""52700""]",alarm,2022-02-25 01:59:36,2022-02-25 09:00:19,2022-02-25 01:00:00,2022-02-25 10:00:00,2022-02-25,1645743600,1645776000

In [36]:
df_events_v2[df_events_v2["type"]=="alarm"].shape

(76232, 14)

In [37]:
#df_events_v2.to_csv("<>", index=False)

Prepare Weather for Merge

In [38]:
WEATHER_DATA_FILE = "<path for weather dataset>"

In [39]:
df_weather = pd.read_csv(WEATHER_DATA_FILE)
df_weather["day_datetime"] = pd.to_datetime(df_weather["day_datetime"])

In [40]:
df_weather.shape

(808944, 65)

In [41]:
weather_exclude = [
"day_feelslikemax",
"day_feelslikemin",
"day_sunriseEpoch",
"day_sunsetEpoch",
"day_description",
"city_latitude",
"city_longitude",
"city_address",
"city_timezone",
"city_tzoffset",
"day_feelslike",
"day_precipprob",
"day_snow",
"day_snowdepth",
"day_windgust",
"day_windspeed",
"day_winddir",
"day_pressure",
"day_cloudcover",
"day_visibility",
"day_conditions",
"day_icon",
"day_source",
"day_preciptype",
"day_stations",
"hour_icon",
"hour_source",
"hour_stations",
"hour_feelslike"
]

In [42]:
df_weather_v2 = df_weather.drop(weather_exclude, axis=1)

In [43]:
df_weather_v2.head(2)

,city_resolvedAddress,day_datetime,day_datetimeEpoch,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipcover,day_solarradiation,day_solarenergy,day_uvindex,day_sunrise,day_sunset,day_moonphase,hour_datetime,hour_datetimeEpoch,hour_temp,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_preciptype,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_visibility,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions
0,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,00:00:00,1645653600,2.4,89.18,0.8,0.0,0.0,0.1,0.2,['snow'],31.3,15.5,275.6,1020.0,0.0,91.5,0.0,NaN,0.0,Overcast
1,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,01:00:00,1645657200,2.4,87.90,0.6,0.0,0.0,0.0,0.2,['snow'],27.7,14.8,280.3,1021.0,0.2,88.2,0.0,NaN,0.0,Partially cloudy

In [44]:
df_weather_v2["city"] = df_weather_v2["city_resolvedAddress"].apply(lambda x: x.split(",")[0])
#df_weather_v2["city"] = df_weather_v2["city"].replace('Хмельницька область', "Хмельницький")

Merging data

In [45]:
df_regions = pd.read_csv("<your path for regions list>")

In [46]:
df_regions.head(5)

             region center_city_ua center_city_en        region_alt  region_id
0           АР Крим    Сімферополь     Simferopol              Крим          1
1         Вінницька        Вінниця      Vinnytsia        Вінниччина          2
2         Волинська          Луцьк          Lutsk            Волинь          3
3  Дніпропетровська         Дніпро         Dnipro  Дніпропетровщина          4
4          Донецька        Донецьк        Donetsk         Донеччина          5

In [47]:
df_weather_reg = pd.merge(df_weather_v2, df_regions, left_on="city",right_on="center_city_ua")

In [48]:
df_weather_reg.head(2)

,city_resolvedAddress,day_datetime,day_datetimeEpoch,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipcover,day_solarradiation,day_solarenergy,day_uvindex,day_sunrise,day_sunset,day_moonphase,hour_datetime,hour_datetimeEpoch,hour_temp,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_preciptype,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_visibility,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions,city,region,center_city_ua,center_city_en,region_alt,region_id
0,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,00:00:00,1645653600,2.4,89.18,0.8,0.0,0.0,0.1,0.2,['snow'],31.3,15.5,275.6,1020.0,0.0,91.5,0.0,NaN,0.0,Overcast,Луцьк,Волинська,Луцьк,Lutsk,Волинь,3
1,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,01:00:00,1645657200,2.4,87.90,0.6,0.0,0.0,0.0,0.2,['snow'],27.7,14.8,280.3,1021.0,0.2,88.2,0.0,NaN,0.0,Partially cloudy,Луцьк,Волинська,Луцьк,Lutsk,Волинь,3

In [49]:
df_weather_reg.shape

(773376, 42)

In [50]:
df_weather_v2.shape

(808944, 37)

Merging weather and events

In [51]:
df_events_v2.dtypes

region_title                        object
region_city                         object
all_region                           int64
start                               object
end                                 object
original_alarms                     object
type                                object
start_time                  datetime64[ns]
end_time                    datetime64[ns]
start_hour                  datetime64[ns]
end_hour                    datetime64[ns]
day_date                            object
start_hour_datetimeEpoch             int64
end_hour_datetimeEpoch               int64
dtype: object

In [52]:
df_events_v2.shape

(76232, 14)

In [53]:
df_events_v2.head(2)

,region_title,region_city,all_region,start,end,original_alarms,type,start_time,end_time,start_hour,end_hour,day_date,start_hour_datetimeEpoch,end_hour_datetimeEpoch
0,Львівська область,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28,"[""52432""]",alarm,2022-02-24 07:43:17,2022-02-24 09:52:28,2022-02-24 07:00:00,2022-02-24 10:00:00,2022-02-24,1645678800,1645689600
1,Чернігівська область,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43,"[""53292""]",alarm,2022-02-24 14:00:43,2022-02-24 17:11:43,2022-02-24 14:00:00,2022-02-24 18:00:00,2022-02-24,1645704000,1645718400

In [54]:
events_dict = df_events_v2.to_dict('records')
events_by_hour = []

In [55]:
events_dict[0]

{'region_title': 'Львівська область',
 'region_city': 'Львівська обл.',
 'all_region': 1,
 'start': '2022-02-24 07:43:17',
 'end': '2022-02-24 09:52:28',
 'original_alarms': '["52432"]',
 'type': 'alarm',
 'start_time': Timestamp('2022-02-24 07:43:17'),
 'end_time': Timestamp('2022-02-24 09:52:28'),
 'start_hour': Timestamp('2022-02-24 07:00:00'),
 'end_hour': Timestamp('2022-02-24 10:00:00'),
 'day_date': datetime.date(2022, 2, 24),
 'start_hour_datetimeEpoch': 1645678800,
 'end_hour_datetimeEpoch': 1645689600}

In [56]:
for event in events_dict:
    for d in pd.date_range(start=event["start_hour"], end=event["end_hour"], freq='1H'):
        et = event.copy()
        et["hour_level_event_time"] = d
        events_by_hour.append(et)

In [57]:
df_events_v3 = pd.DataFrame.from_dict(events_by_hour)

In [58]:
df_events_v3["hour_level_event_datetimeEpoch"] = df_events_v3["hour_level_event_time"].apply(
    lambda x: int(x.timestamp()) if pd.notna(x) else None
)

In [59]:
df_events_v3.head(2)

,region_title,region_city,all_region,start,end,original_alarms,type,start_time,end_time,start_hour,end_hour,day_date,start_hour_datetimeEpoch,end_hour_datetimeEpoch,hour_level_event_time,hour_level_event_datetimeEpoch
0,Львівська область,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28,"[""52432""]",alarm,2022-02-24 07:43:17,2022-02-24 09:52:28,2022-02-24 07:00:00,2022-02-24 10:00:00,2022-02-24,1645678800,1645689600,2022-02-24 07:00:00,1645686000
1,Львівська область,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28,"[""52432""]",alarm,2022-02-24 07:43:17,2022-02-24 09:52:28,2022-02-24 07:00:00,2022-02-24 10:00:00,2022-02-24,1645678800,1645689600,2022-02-24 08:00:00,1645689600

In [60]:
df_weather_reg.head(5)

,city_resolvedAddress,day_datetime,day_datetimeEpoch,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipcover,day_solarradiation,day_solarenergy,day_uvindex,day_sunrise,day_sunset,day_moonphase,hour_datetime,hour_datetimeEpoch,hour_temp,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_preciptype,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_visibility,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions,city,region,center_city_ua,center_city_en,region_alt,region_id
0,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,00:00:00,1645653600,2.4,89.18,0.8,0.0,0.0,0.1,0.2,['snow'],31.3,15.5,275.6,1020.0,0.0,91.5,0.0,NaN,0.0,Overcast,Луцьк,Волинська,Луцьк,Lutsk,Волинь,3
1,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,01:00:00,1645657200,2.4,87.90,0.6,0.0,0.0,0.0,0.2,['snow'],27.7,14.8,280.3,1021.0,0.2,88.2,0.0,NaN,0.0,Partially cloudy,Луцьк,Волинська,Луцьк,Lutsk,Волинь,3
2,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,02:00:00,1645660800,2.9,88.58,1.2,0.0,0.0,0.0,0.1,['snow'],29.2,14.4,310.0,1022.0,10.0,100.0,NaN,NaN,NaN,Overcast,Луцьк,Волинська,Луцьк,Lutsk,Волинь,3
3,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,03:00:00,1645664400,2.3,86.63,0.3,0.0,0.0,0.0,0.1,['snow'],23.8,13.3,295.1,1021.0,0.1,92.0,0.0,NaN,0.0,Overcast,Луцьк,Волинська,Луцьк,Lutsk,Волинь,3
4,"Луцьк, Луцький район, Україна",2022-02-24,1645653600,4.9,0.7,2.6,0.0,83.7,0.118,4.17,36.9,2.8,1.0,07:13:36,17:51:06,0.77,04:00:00,1645668000,1.9,87.85,0.1,0.0,0.0,0.0,0.1,['snow'],24.5,13.3,305.8,1021.0,0.0,93.8,0.0,NaN,0.0,Overcast,Луцьк,Волинська,Луцьк,Lutsk,Волинь,3

In [61]:
df_events_v4 = df_events_v3.copy().add_prefix('event_')

In [62]:
df_weather_v4 = df_weather_reg.merge(df_events_v4, 
                                     how="left", 
                                     left_on=["region_alt","hour_datetimeEpoch"],
                                     right_on=["event_region_city","event_hour_level_event_datetimeEpoch"])

In [63]:
#df_weather_v4.to_csv("<>", sep=";", index=False)

In [64]:
df_weather_v4.shape

(773376, 58)