In [1]:
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
import nltk
import os
import string
import numpy as np
import copy 
import pickle
import re
import math

import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from collections import Counter
from num2words import num2words


from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

data = pd.read_csv("<your path for prepared isw dataset>")

In [2]:
data.head()

,Unnamed: 0,id,date,short_url,title,text_title,full_url,html_content,html_content_v6
0,1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."
1,1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."
2,181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."
3,197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."
4,1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."

Functions preparing

In [3]:
def remove_one_letter_word(data):
    words = word_tokenize(str(data))
    
    new_text = ""
    for w in words:
        if (len(w) > 1):
            new_text = new_text + " " + w
            
    return new_text

In [4]:
def convert_lower_case(data):
    return np.char.lower(data)

In [5]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
print(stop_words)

{'have', 'be', "you've", 'again', 'for', 'at', 've', 'before', "i'd", 'having', 'o', 'of', 'been', 'me', 'ma', "couldn't", "didn't", 'this', 'down', 'out', 'own', 'herself', 'in', 'shouldn', 'couldn', "won't", 'further', "it'd", 'only', 'until', 'against', 'being', 'off', "haven't", "it'll", 'their', 'don', 'aren', 'haven', "she'll", "you'll", 'these', 'the', 'our', "we're", 'or', 'those', "we'll", 'weren', "it's", "weren't", 'won', 'from', 'each', 'whom', 'because', 'hers', 'does', "isn't", 'it', 'do', 'into', 'his', 'up', 'isn', 'on', 'very', 'you', 'were', 'why', "aren't", "hadn't", 'mustn', 'had', 't', 'has', 'what', 'some', 'nor', "i'll", "they'd", 'below', 'd', 'yourselves', 'shan', "hasn't", 'ain', 'more', 'while', 'how', 'needn', "wasn't", 'no', "they're", 'they', 'themselves', 'after', 'mightn', 'by', 'doesn', 'but', "needn't", 'over', 'just', 'i', 'itself', 'didn', "don't", 'such', 'under', 'through', 'here', 'your', 'am', 'that', 'y', 'with', 'yourself', 'during', 'should', 'is', 'theirs', 'them', 'too', "shouldn't", 'both', 'there', 'an', 'did', 'm', "she's", 'can', "she'd", 'once', "shan't", "they'll", 'who', "they've", 'hadn', 'himself', 'as', 'its', 's', 'when', 'will', 'so', 'he', "doesn't", "mustn't", 'where', 'my', 'not', 'about', 'him', 'which', "mightn't", 'ours', 'wouldn', "you're", 'yours', "i've", "he'll", 'and', 'than', 'are', "he's", 'her', "that'll", 'most', 'll', "wouldn't", 'between', 'few', "you'd", 'any', 'myself', 'hasn', 'a', 'other', 're', 'then', "we'd", 'ourselves', 'wasn', "i'm", 'to', 'same', 'was', 'now', 'all', 'we', 'she', "we've", 'above', 'if', "should've", "he'd", 'doing'}

[nltk_data] Downloading package stopwords to /Users/mac/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [6]:
def remove_stop_words(data):
    stop_words = set(stopwords.words('english'))
    stop_stop_words = {"no","not"}
    
    stop_words = stop_words - stop_stop_words
    
    words = word_tokenize(str(data))
    
    new_text = ""
    for w in words:
        if w not in stop_words and len(w) > 1:
            new_text = new_text + " " + w
            
    return new_text

In [7]:
def remove_punctuations(data):
    symbols = " !()-[]{};:'\,<>./?@#$%^&*_~ '"""  
    
    for i in range(len(symbols)):
        data = np.char.replace(data,symbols[i]," ")
        data = np.char.replace(data,"  "," ")
    
    data = np.char.replace(data,",", " ")
    
    return data

In [8]:
def stemming(data):
    stemmer = PorterStemmer()
    
    tokens = word_tokenize(str(data))
    new_text = ""
    for w in tokens:
        new_text = new_text + " " + stemmer.stem(w)
        
    return new_text

def lemmatizing(data):
    lemmatizer = WordNetLemmatizer()
    
    tokens = word_tokenize(str(data))
    new_text = ""
    for w in tokens:
        new_text = new_text + " " + lemmatizer.lemmatize(w)
               
    return new_text

In [9]:
def convert_numbers(data):
    
    tokens = word_tokenize(str(data))
    new_text = ""
    for w in tokens:
        if w.isdigit():
            if int(w) < 1000000000:
                w = num2words(w)
            else:
                w = " "
        new_text = new_text + " " + w
            
    new_text = np.char.replace(new_text,"-"," ")
        
    return new_text

In [10]:
def remove_url_from_string(data):
    words = word_tokenize(str(data))
    new_text = ""

    
    for w in words:
        w = re.sub(r'https?:\/\/.*[\r\n]*',"",str(w),flags=re.MULTILINE)
        w = re.sub(r'http?:\/\/.*[\r\n]*',"",str(w),flags=re.MULTILINE)
        
        new_text = new_text + " " + w
        
    return new_text

In [11]:
def preprocess(data, word_root_algo='lemm'):
    
    data = remove_one_letter_word(data)
    data = convert_lower_case(data)
    data = remove_stop_words(data)
    data = stemming(data)
    data = remove_punctuations(data)
    data = convert_numbers(data)
    data = remove_url_from_string(data)
    
    if word_root_algo =='lemm':
        data = lemmatizing(data)
    else: 
        data = stemming(data)
        
    
    data = remove_punctuations(data)
    data = remove_stop_words(data)
    
    return data

In [12]:
#nltk.download('punkt')
#nltk.download('wordnet')
data['report_text_lemm'] = data['html_content_v6'].apply(lambda x: preprocess(x,"lemm"))

In [13]:
data['report_text_stemm'] = data['html_content_v6'].apply(lambda x: preprocess(x,"stemm"))

In [14]:
data.head()

,Unnamed: 0,id,date,short_url,title,text_title,full_url,html_content,html_content_v6,report_text_lemm,report_text_stemm
0,1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty f...,russian offen campaign assess februari twenti...
1,1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty f...,russian offen campaign assess februari twenti...
2,181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty s...,russian offen campaign assess februari twenti...
3,197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty s...,russian offen campaign assess februari twenti...
4,1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty e...,russian offen campaign assess februari twenti...

In [15]:
data['report_text_lemm'][0]

' russian offens campaign ass februari twenty four two thousand twenty five isw option download page print pageshareskip contentskip content donat menu menu iswabout iswour capabilitiesisw compar advantageour historyimprov nation secur debatewho aremeet teamcareersjoin missionopen positionsmap roomisw produc world premier open sourc conflict map see mapsanalysisanalysisth gener jack kean center nation securitymap roomdiv isw complet map catalogbrief roomvideo podcast interact contentresearch librarybrows isw entir bodi workteams portfoliosrussia ukrainemiddl eastchina taiwandefens europeadversari ententecontemporari futur wargeospati intelligencecognit warfareeducationeducationth gener david petraeu center emerg leadershertog war studiesisw premier educ program undergraduatesfellowshipsenrich advanc opportun entry level mid car professionalsinternshipslaunch career isw internship open sourc intellig geospati intellig cognit warfar communicationsresearch librarybrows isw publish work curat maximum searchabl view insightsget involvedget involvedjoin isw commun help safeguard america securitydonateyour donat keep isw independ nonpartisan objectiveplan givingsecur legaci strengthen futur generationsour partnerspartn isw make direct impact america secur futur leadersnewsroom donat russia ukraineukrainerussian offens campaign assessmentrussian offens campaign ass februari twenty four 2025februari twenty five 2025jump topreviousnextrussian offens campaign ass februari twenty four 2025russian offens campaign ass februari twenty four 2025angelica evan christina harward nicol wolkov olivia gibson frederick kagan nate trotterfebruari twenty four two thousand twenty five seven forty pm et click see isw interact map russian invas ukrain map updat daili alongsid static map present report click see isw interact map ukrain offens kursk oblast click see isw 3d control terrain topograph map ukrain use comput not mobil devic strongli recommend use data heavi tool click access isw archiv interact time lap map russian invas ukrain map complement static control terrain map isw produc daili show dynam frontlin isw updat time lap map archiv monthly not data cut product eleven 30am et februari twenty four isw cover subsequ report februari twenty five russian offens campaign assessment russian presid vladimir putin order unprovok full scal invas ukrain three year ago februari twenty four ukrain not defeat destroy remain resili innov face unjustifi russian aggress putin launch full scal invas ukrain fail attempt seiz kyiv citi overthrow ukrain democrat elect govern forcibl instal pro russian proxi govern three day ukrainian forc support coalit alli includ unit state european partner sinc success push russian forc northern ukrain liber signific territori southern northeastern ukrain ukrainian commander chief gener oleksand syrskyi report februari twenty four ukrainian forc regain fifty percent territori russian forc occupi sinc februari twenty four isw observ confirm ukrainian forc regain fifty three percent territori russian forc seiz sinc februari twenty four russian forc spent last year make slow increment steadi advanc eastern ukrain result signific russian manpow materiel advantag russia abil leverag delay western aid ukrain ukrainian forc use technolog advantag integr technolog innov ground oper order slow russian gain ukrain continu improv innov warfight capabl work becom self suffici long term western intern militari support ukrain short medium term remain crucial ukrain abil defend russian aggress defens ukrain preserv ukrain independ sovereign democrat countri capabl defend russia critic part deter broader russian aggress west unit state europ western alli must demonstr commit ukrain time reliabl militari assist continu enabl ukrainian forc impos signific pressur russia forc putin abandon conquest ukrain wider ambit europ order bring sustain peace russia accumul unsustain personnel vehicl loss last three year sinc russia full scal invas februari twenty four ukrainian commander chief gener oleksand syrskyi report februari twenty four russian forc lost ten one hundred tank twenty one one hundred armor combat vehicl twenty three three hundred artilleri system presum destroy damag three year russia full scal invas british intern institut strateg studi iis recent estim russia lost fourteen zero tank infantri fight vehicl armor personnel carrier sinc februari iis number like differ syrskyi iis data like account destroy vehicl syrskyi state februari twenty four russian forc lost almost eight hundred seventy zero personnel includ two hundred fifty zero dead russian opposit outlet meduza mediazona publish joint report februari twenty four wherein use russian regist inherit case rnd estim least one hundred sixty zero one hundred sixty five zero russian servicememb die past three year war syrskyi previous report russian forc suffer four hundred thirty four zero casualti two thousand twenty four alon meduza mediazon estim februari two thousand twenty four russia lost least sixty six zero eighty eight zero personnel first two year war suggest russian lose significantli increas two thousand twenty four isw continu ass russian forc suffer vehicl artilleri system loss battlefield unsustain medium long term given limit russia defens industri capac soviet era weapon equip stock russia forc gener apparatu struggl recruit enough soldier sustain russia current rate offens oper loss rate th unit nation un gener assembl pas ukrainian european back resolut februari twenty four commemor third anniversari russia full scal invas ukrain recogn russia aggressor war call peac ukrain support ukrain sovereignti territori integr unit state russia belaru north korea fourteen countri vote ukrainian european back resolut ninety three countri support peopl republ china iran abstain unit state also abstain second resolut third anniversari war propos european countri amend resolut add languag support ukrain sovereignti independ uniti territori integr back draft resolut prior european amend reportedli not acknowledg russia role aggressor refer russia war ukrain russian federation ukrain conflict recent poll indic russian increasingli support russia continu war ukrain achiev complet ukrainian capitul simultan start feel econom toll three year russia war cast doubt russian presid vladimir putin abil continu balanc butter gun home medium long term recent poll conduct independ russian opposit poll organ chronicl februari thirteen show forty six percent respond not support withdraw russian troop ukrain without russia achiev war goal number respond not support russian withdraw consist decreas februari forty seven percent septemb two thousand twenty four thirty one percent jump back februari level februari two thousand twenty five fifty four percent respond februari two thousand twenty five state war neg affect daili live thirty six percent respond state financi situat worsen increas twenty seven percent septemb two thousand twenty four thirty six percent respond februari two thousand twenty five state russian govern priorit militari spend budget decreas forty three percent septemb two thousand twenty four number respond state import area russian spend social sphere increas thirty eight percent septemb two thousand twenty four forty eight percent februari two thousand twenty five kremlin rhetor rel faster russian tempo advanc battlefield recent month continu offici statement need ukrain denazifi demilitar declar neutral putin origin state war aim like influenc russian reject withdraw belief russia achiev object continu fight russia protract war ukrain howev strain russia economi includ increas inflat spend russia sovereign wealth fund exacerb exist labor shortag russia like face number materiel manpow econom issu twelve eighteen month ukrainian forc continu inflict damag russian forc battlefield current rate like increas econom burden russian popul feel future russian presid vladimir putin current remain commit continu war ukrain despit rise domest polit econom pressur shown no indic rethink determin compel ukrain surrend russian state medium larg ignor third anniversari full scal invas program februari twenty four instead highlight meet russian central spiritu director muslim chairman suprem mufti talgat tadzhuddin prais putin announc conduct war ukrain putin kremlin offici not abandon origin war aim ukrain continu invok goal denazifi demilitar ukrain ban ukrain abil join secur bloc futur despit russia failur defeat ukrain militarili last three year putin not appear deter idea protract war despit suffer signific like unsustain personnel materiel loss last three year isw recent note russian militari appear employ method advanc ukrain base assumpt war continu indefinit russian militari not need make rapid signific territori gain singl offens oper isw recent ass would take russian forc eighty three year captur remain eighty percent ukrain assum sustain current rate advanc massiv personnel loss indefinit unlik putin articul theori victori howev assum russia outlast ukrain west continu advanc battlefield russia defeat ukrain putin recent statement reject possibl peac agreement ukrain indic willing protract war putin continu signal russian militari societi not end war ukrain capitul complet no interest negoti peac agreement requir russia compromis long stand war aim despit putin effort signal interest peac negoti western leader kremlin offici formal reject possibl ceasefir term complet capitul ukrain west februari twenty four underscor russia unwilling make compromis futur peac negoti russian foreign minist sergei lavrov claim februari twenty four press confer turkey russia stop militari activ ukrain peac negoti bring solid stabl result suit russia account realiti battlefield lavrov note peac agreement must includ provis ban ukrain join nato futur russian state medium tv channel channel one pervyi kanal summar lavrov statement russia end combat oper negoti end way satisfi russia russian deputi foreign minist sergei ryabkov told russian state newswir ria novosti februari twenty four russia not agre ceasefir not address root caus war ryabkov state ceasefir not address war root caus path quick resumpt war reiter russia consid nato post one thousand nine hundred ninety one eastward expans root caus war kremlin spokesperson dmitri peskov also claim februari twenty four would imposs resolv war ukrain without understand address root caus kremlin offici repeatedli allud need futur peac negoti address root caus war ukrain lavrov defin decemb two thousand twenty four nato alleg violat commit not advanc eastward aggress absorpt area near russia border ukrainian govern alleg discrimin ethnic russian within ukraine russian offici also continu frame russia demand ukrainian forc withdraw territori ukrainian forc current control eastern southern ukrain compromis ryabkov state russian presid vladimir putin june two thousand twenty four demand ukrain complet withdraw ukrainian control territori donetsk luhansk zaporizhia kherson oblast abandon goal join nato contain signific compromis could serv base futur peac agreement ryabkov claim putin june two thousand twenty four demand highlight russia desir find resolut war balanc russia ukrain interest despit fact putin call ukrain conced signific area exchang no russian concess isw previous note ukrainian author reject istanbul protocol term effect amount full ukrainian surrend ukrainian author like reject futur ceasefir peac agreement amount european leader announc seri new aid packag visit kyiv februari twenty four third anniversari full scal invas februari twenty four canadian prime minist justin trudeau announc new militari aid packag ukrain consist twenty five infantri fight vehicl two armor combat vehicl land system sixteen fighter jet four sixteen flight simul ammunit drone camera compon first aid kit swedish offici recent announc plan provid ukrain unspecifi number robotsystem seventy tridon mk2 air defens system valu approxim one hundred thirteen million lithuanian presid gitana nauseda announc plan deliv unspecifi number rb seventy short rang air defens system ukrain estonian prime minist kristen michal announc militari aid packag consist ten zero round artilleri ammunit seven hundred fifty zero ration packag irish prime minist micheal martin announc plan suppli ukrain unspecifi number older air defens radar system european commiss presid ursula von der leyen announc eu financi aid packag ukrain valu three five billion euro three six billion eu distribut march two thousand twenty five british prime minist keir starmer announc uk provid ukrain four five billion pound five six billion militari aid spanish prime minist pedro sanchez pledg spain deliv new militari aid packag ukrain worth estim one billion euro one five billion part broader ten year bilater secur defens agreement ukrain spain sign may two thousand twenty four iceland prime minist kristrún mjöll frostadóttir pledg increas iceland monetari support ukrain roughli fourteen four million euro fifteen million key takeaway russian presid vladimir putin order unprovok full scal invas ukrain three year ago februari twenty four ukrain not defeat destroy remain resili innov face unjustifi russian aggression russia accumul unsustain personnel vehicl loss last three year sinc russia full scal invas februari twenty four unit nation un gener assembl pas ukrainian european back resolut februari twenty four commemor third anniversari russia full scal invas ukrain recogn russia aggressor war call peac ukrain support ukrain sovereignti territori integrity rec poll indic russian increasingli support russia continu war ukrain achiev complet ukrainian capitul simultan start feel econom toll three year russia war cast doubt russian presid vladimir putin abil continu balanc butter gun home medium long term russian presid vladimir putin current remain commit continu war ukrain despit rise domest polit econom pressur shown no indic rethink determin compel ukrain surrender kremlin offici formal reject possibl ceasefir term complet capitul ukrain west februari twenty four underscor russia unwilling make compromis futur peac negotiation european leader announc seri new aid packag visit kyiv februari twenty four third anniversari full scal invas februari twenty four russian forc recent advanc kursk oblast near chasiv yar pokrovsk velyka novosilka kremlin continu use muslim religi cultur structur russia militari recruitment not report detail russian war crime activ well cov western medium not directli affect militari oper ass forecast continu evalu report effect crimin activ ukrainian militari ukrainian popul specif combat ukrainian urban area utterli condemn russian violat law arm conflict geneva convent crime human even though not describ report ukrainian oper russian federationrussian main effort eastern ukrain compris three subordin main effort russian subordin main effort push ukrainian forc back intern border belgorod oblast approach within tube artilleri rang kharkiv cityrussian subordin main effort captur remaind luhansk oblast push westward eastern kharkiv oblast encircl northern donetsk oblastrussian subordin main effort captur entireti donetsk oblastrussian support effort southern axisrussian air missil drone campaignrussian mobil forc gener effortsrussian technolog adaptationsact russian occupi areassignific activ belarusukrainian oper russian federationrussian forc recent advanc kursk oblast russian forc attack near intern border northeastern sumi oblast near zhuravka northwest sudzha near sverdlikovo lebedevka nikolskiy malaya loknya pogrebki southeast sudzha near cherkasskaya konopelka fanaseyevka kremlin affili russian milblogg claim februari twenty four ukrainian forc counterattack along seven yunakivka sudzha road ass russian advanc geoloc footag publish februari twenty three indic russian forc recent advanc western lebedevka unconfirm russian claim advanc russian milblogg claim element russian 34th motor rifl brigad 49th combin arm armi caa southern militari district smd advanc near pogrebki element 51st airborn vdv regiment 137th vdv regiment 106th vdv divis advanc within lebedevka element 1427th motor rifl regiment form partial reserv call advanc near kositsa north sudzha order battl element russian 119th vdv regiment 106th vdv divis reportedli oper near sverdlikovo element 1st battalion 9th motor rifl regiment 18th motor rifl divis 11th armi corp ac leningrad militari district lmd reportedli oper near pogrebki element 30th motor rifl regiment 72nd motor rifl divis 44th ac lmd 51st vdv regiment 106th vdv divis reportedli oper near sudzha element 177th naval infantri regiment caspian flotilla kamerton detach akhmat spetsnaz reportedli oper kursk oblast drone oper rubicon center advanc technolog reportedli oper kursk oblast ukrainian forc conduct drone strike russian oil ga infrastructur ryazan tula oblast februari twenty three night februari twenty three twenty four ukrainian gener staff report ukrain unman system forc main militari intellig director gur ukrainian forc struck ryazan oil refineri ryazan citi night februari twenty three twenty four head ukrain center combat disinform lieuten andriy kovalenko state ryazan oil refineri one five largest oil refineri russia process capac seventeen one million ton oil per year refineri produc gasolin diesel fuel fuel oil jet fuel petrochem kovalenko note ukrainian forc previous struck ryazan oil refineri night januari twenty three twenty four januari twenty five twenty six ryazan oblast governor pavel malkov claim drone debri land territori unspecifi enterpris ryazan oblast ukrainian gener staff also report ukrainian unman system forc struck oil depot caus fire near marta plant near uzlovaya tula oblast februari twenty three tula oblast governor dmitri milayev claim russian electron warfar ew repel two drone uzlovski kireevski raion night februari twenty two twenty three russian main effort eastern ukrainerussian subordin main effort kharkiv oblast russian object push ukrainian forc back intern border belgorod oblast approach within tube artilleri rang kharkiv citi russian forc continu offens oper kharkiv direct februari twenty four not advanc russian forc conduct offens oper northeast kharkiv citi near vovchansk februari twenty three twenty four order battl artilleri element russian 41st motor rifl regiment 72nd motor rifl divis 44th armi corp leningrad militari district bati group chechen akhmat spetsnaz reportedli oper kharkiv direction russian subordin main effort luhansk oblast russian object captur remaind luhansk oblast push westward eastern kharkiv oblast northern donetsk oblast kupyansk russian forc continu offens oper kupyansk direct februari twenty four not advanc russian forc attack north kupyansk near zapadn northeast kupyansk near dvorichna fyholivka east kupyansk near petropavlivka februari twenty three twenty four kremlin affili russian milblogg claim ukrainian forc maintain limit posit dvorichna unconfirm russian claim advanc russian ministri defens mod claim februari twenty four russian forc seiz topoli northeast kupyansk command ukrainian drone crew oper kupyansk lyman line report russian forc attempt advanc small infantri group ukrainian forc destroy seventy eighty percent russian assault group way frontlin accumul point command note russian forc use larg number first person view fpv drone fiber opt cable ord battl ukrainian militari observ kostyantyn mashovet report element 69th motor rifl divis 6th combin arm armi caa leningrad militari district lmd oper near dvorichna novomlynsk northeast dvorichna element russian 27th motor rifl brigad 1st guard tank armi gta moscow militari district mmd reportedli oper kupyansk direction russian forc continu offens oper borova direct februari twenty four not advanc russian forc attack northeast borova near zahryzov toward novoplatonivka borivska andriivka bohuslavka east borova near kopanki tow

In [16]:
docs = data['report_text_lemm'].tolist()

In [17]:
#data.to_csv("")

CountVectorizer

In [18]:
cv = CountVectorizer(max_df=0.98,min_df=2)
word_count_vector = cv.fit_transform(docs)

word_count_vector.shape

(1464, 14252)

In [19]:
data.head(10)

,Unnamed: 0,id,date,short_url,title,text_title,full_url,html_content,html_content_v6,report_text_lemm,report_text_stemm
0,1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty f...,russian offen campaign assess februari twenti...
1,1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty f...,russian offen campaign assess februari twenti...
2,181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty s...,russian offen campaign assess februari twenti...
3,197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty s...,russian offen campaign assess februari twenti...
4,1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar...",russian offens campaign ass februari twenty e...,russian offen campaign assess februari twenti...
5,547,548,2022-03-01,2022_03_01,"Russian Offensive Campaign Assessment, March 1...","Russian Offensive Campaign Assessment, March 1...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, March 1...",russian offens campaign ass march isw option ...,russian offen campaign assess march isw optio...
6,998,999,2022-03-02,2022_03_02,"Russian Offensive Campaign Assessment, March 2...","Russian Offensive Campaign Assessment, March 2...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, March 2...",russian offens campaign ass march isw option ...,russian offen campaign assess march isw optio...
7,838,839,2022-03-03,2022_03_03,"Russian Offensive Campaign Assessment, March 3...","Russian Offensive Campaign Assessment, March 3...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, March 3...",russian offens campaign ass march isw option ...,russian offen campaign assess march isw optio...
8,1454,1455,2022-03-04,2022_03_04,"Russian Offensive Campaign Assessment, March 4...","Russian Offensive Campaign Assessment, March 4...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, March 4...",russian offens campaign ass march isw option ...,russian offen campaign assess march isw optio...
9,1110,1111,2022-03-05,2022_03_05,"Russian Offensive Campaign Assessment, March 5...","Russian Offensive Campaign Assessment, March 5...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, March 5...",russian offens campaign ass march isw option ...,russian offen campaign assess march isw optio...

In [20]:
word_count_vector

<1464x14252 sparse matrix of type '<class 'numpy.int64'>'
	with 939878 stored elements in Compressed Sparse Row format>

In [21]:
with open(r"count_vectorizer_v1.pkl", "wb") as handle:
    pickle.dump(cv, handle)

TF-IDF

In [22]:
tfidf_transformer = TfidfTransformer(smooth_idf = True, use_idf = True)
tfidf_transformer.fit(word_count_vector)

TfidfTransformer()

In [23]:
with open("tfidf_transformer.pkl","wb") as handle:
    pickle.dump(tfidf_transformer, handle)

In [24]:
df_idf = pd.DataFrame(tfidf_transformer.idf_, index = cv.get_feature_names_out(),columns=["idf_weights"])
df_idf.sort_values(by=['idf_weights'])

                idf_weights
territori          1.024880
assessmentread     1.024880
missionopen        1.024880
captur             1.024880
defens             1.024880
...                     ...
lazutkin           6.680173
layout             6.680173
layoff             6.680173
lax                6.680173
сухопутный         6.680173

[14252 rows x 1 columns]

In [25]:
tf_idf_vector = tfidf_transformer.transform(word_count_vector)

In [26]:
tf_idf_vector

<1464x14252 sparse matrix of type '<class 'numpy.float64'>'
	with 939878 stored elements in Compressed Sparse Row format>

Transformation with fitted models

In [27]:
tfidf = pickle.load(open("tfidf_transformer.pkl","rb"))
cv = pickle.load(open("count_vectorizer_v1.pkl","rb"))

In [28]:
feature_names = cv.get_feature_names_out()

In [29]:
feature_names

array(['000km', '00pm', '02owivyrp402xkkwk', ..., 'программа',
       'підрозділи', 'сухопутный'], dtype=object)

In [30]:
def sort_coo(coo_matrix):
    
    tuples = zip(coo_matrix.col, coo_matrix.data)
    
    return sorted(tuples,key=lambda x: (x[1], x[0]), reverse=True)

def extract_topn_from_vector(feature_names, sorted_items, topn=10):
    
    sorted_items = sorted_items[:topn]
    
    score_vals = []
    feature_vals = []
    
    for idx, score in sorted_items:
        
        score_vals.append(round(score,3))
        feature_vals.append(feature_names[idx])
        
    results = {}
    
    for idx in range(len(feature_vals)):
        results[feature_vals[idx]] = score_vals[idx]
    
    return results


def convert_doc_to_vector(doc):
    feature_names = cv.get_feature_names_out()
    top_n = 10
    tf_idf_vector = tfidf.transform(cv.transform([doc]))
    
    sorted_items = sort_coo(tf_idf_vector.tocoo())
    
    keywords = extract_topn_from_vector(feature_names, sorted_items, top_n)
    
    return keywords

In [31]:
data['keywords'] = data['report_text_stemm'].apply(lambda x: convert_doc_to_vector(x))

In [32]:
data['keywords'][0]

{'twenti': 0.897,
 'februari': 0.205,
 'hundr': 0.142,
 'near': 0.071,
 'motor': 0.07,
 'rifl': 0.069,
 'thirti': 0.059,
 'percent': 0.052,
 'pokrovsk': 0.052,
 'eighti': 0.051}

In [33]:
data_vectorised = tf_idf_vector.toarray()

In [34]:
vectors_df = pd.DataFrame(data_vectorised)

In [35]:
#vectors_df.to_csv("")